
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - http://localhost:4000/gseptik-card.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Load integrations
demo:

# Include extra configuration
rest: !include rests.yaml
