# Setup cache
cache:
  untracked: true

# Setup stages
stages:
  - build

# Build artifacts
build-application:
  stage: build
  tags:
    - linux
  script:
    - git rev-parse HEAD > VERSION
  artifacts:
    name: artifacts
    expire_in: 1 week
    paths:
      - VERSION
