#
# Package (build and test) application
#
name: Package Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install npm packages
        shell: bash
        run: npm install
      - name: Run eslint commands
        shell: bash
        run: npm run lint
      - name: Run prettier commands
        shell: bash
        run: npm run prettier
      - name: Run HACS validation
        uses: hacs/action@main
        env:
          ACTIONS_STEP_DEBUG: "true"
        with:
          category: plugin
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install npm packages
        shell: bash
        run: npm install
      - name: Run build commands
        shell: bash
        run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install npm packages
        shell: bash
        run: npm install
      - name: Run vitest commands
        shell: bash
        run: npm run test
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install npm packages
        shell: bash
        run: npm install
      - name: Run coverage commands
        shell: bash
        run: npm run test:coverage
